version: '3.8'

services:
  nestjs-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: nestjs.app
        fluentd-async: "true"
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - fluentd

  fluentd:
    build:
      context: ./fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/logs:/fluentd/log
    environment:
      - FLUENTD_CONF=fluent.conf
    networks:
      - monitoring
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=false
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - loki

volumes:
  grafana-storage:
  loki-data:

networks:
  monitoring:
    driver: bridge
